"""Bring your own browser to Playwright."""

from ._chrome import (
    CHROME_PATH_ENV,
    DEFAULT_CHANNEL,
    DEFAULT_CHROME_ARGS,
    DEFAULT_IGNORE_DEFAULT_ARGS,
    DEFAULT_PROFILE_DIRECTORY,
    PROFILE_DIRECTORY_ENV,
    USER_DATA_DIR_ENV,
    ChromeLaunchConfig,
    ChromeNotFoundError,
    ChromeProfileInUseError,
    ChromeProfileNotFoundError,
    ConfigurationError,
    IgnoreDefaultArgs,
    PathLike,
    PathSetting,
    PlaywrightByobError,
    ProfileSetting,
    async_launch_chrome,
    build_chrome_launch_config,
    chrome_executable_candidates,
    chrome_user_data_dir_candidates,
    detect_chrome_executable,
    detect_chrome_user_data_dir,
    launch_chrome,
)

__all__ = [
    "CHROME_PATH_ENV",
    "DEFAULT_CHANNEL",
    "DEFAULT_CHROME_ARGS",
    "DEFAULT_IGNORE_DEFAULT_ARGS",
    "DEFAULT_PROFILE_DIRECTORY",
    "PROFILE_DIRECTORY_ENV",
    "USER_DATA_DIR_ENV",
    "ChromeLaunchConfig",
    "ChromeNotFoundError",
    "ChromeProfileInUseError",
    "ChromeProfileNotFoundError",
    "ConfigurationError",
    "IgnoreDefaultArgs",
    "PathLike",
    "PathSetting",
    "ProfileSetting",
    "PlaywrightByobError",
    "async_launch_chrome",
    "build_chrome_launch_config",
    "chrome_executable_candidates",
    "chrome_user_data_dir_candidates",
    "detect_chrome_executable",
    "detect_chrome_user_data_dir",
    "launch_chrome",
]
